
version: '3'
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ilias
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: work_db
      POSTGRES_URL: "${DB_HOST}"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ilias@1337.com
      PGADMIN_DEFAULT_PASSWORD: 1337

  pingpong-app:
    build: ./
    container_name: pingpong
    ports:
      - 5000:5000
      - 3000:3000
    links:
      - db